import { useQuery } from '@tanstack/react-query';
import api from '@/lib/api';

export interface District {
  id: string;
  name: string;
  name_bn: string;
  division: string | null;
}

export interface Upazila {
  id: string;
  district_id: string;
  name: string;
  name_bn: string;
}

export interface DeliverySetting {
  id: string;
  delivery_type: 'inside_dhaka' | 'outside_dhaka';
  charge: number;
  status: boolean;
}

const bangladeshDistricts: District[] = [
  { id: 'dhaka', name: 'Dhaka', name_bn: 'ঢাকা', division: 'Dhaka' },
  { id: 'gazipur', name: 'Gazipur', name_bn: 'গাজীপুর', division: 'Dhaka' },
  { id: 'narayanganj', name: 'Narayanganj', name_bn: 'নারায়ণগঞ্জ', division: 'Dhaka' },
  { id: 'narsingdi', name: 'Narsingdi', name_bn: 'নরসিংদী', division: 'Dhaka' },
  { id: 'manikganj', name: 'Manikganj', name_bn: 'মানিকগঞ্জ', division: 'Dhaka' },
  { id: 'munshiganj', name: 'Munshiganj', name_bn: 'মুন্সীগঞ্জ', division: 'Dhaka' },
  { id: 'madaripur', name: 'Madaripur', name_bn: 'মাদারীপুর', division: 'Dhaka' },
  { id: 'shariatpur', name: 'Shariatpur', name_bn: 'শরীয়তপুর', division: 'Dhaka' },
  { id: 'faridpur', name: 'Faridpur', name_bn: 'ফরিদপুর', division: 'Dhaka' },
  { id: 'gopalganj', name: 'Gopalganj', name_bn: 'গোপালগঞ্জ', division: 'Dhaka' },
  { id: 'kishoreganj', name: 'Kishoreganj', name_bn: 'কিশোরগঞ্জ', division: 'Dhaka' },
  { id: 'tangail', name: 'Tangail', name_bn: 'টাঙ্গাইল', division: 'Dhaka' },
  { id: 'chittagong', name: 'Chittagong', name_bn: 'চট্টগ্রাম', division: 'Chittagong' },
  { id: 'comilla', name: 'Comilla', name_bn: 'কুমিল্লা', division: 'Chittagong' },
  { id: 'feni', name: 'Feni', name_bn: 'ফেনী', division: 'Chittagong' },
  { id: 'brahmanbaria', name: 'Brahmanbaria', name_bn: 'ব্রাহ্মণবাড়িয়া', division: 'Chittagong' },
  { id: 'chandpur', name: 'Chandpur', name_bn: 'চাঁদপুর', division: 'Chittagong' },
  { id: 'lakshmipur', name: 'Lakshmipur', name_bn: 'লক্ষ্মীপুর', division: 'Chittagong' },
  { id: 'noakhali', name: 'Noakhali', name_bn: 'নোয়াখালী', division: 'Chittagong' },
  { id: 'cox_bazar', name: "Cox's Bazar", name_bn: 'কক্সবাজার', division: 'Chittagong' },
  { id: 'rangamati', name: 'Rangamati', name_bn: 'রাঙ্গামাটি', division: 'Chittagong' },
  { id: 'bandarban', name: 'Bandarban', name_bn: 'বান্দরবান', division: 'Chittagong' },
  { id: 'khagrachhari', name: 'Khagrachhari', name_bn: 'খাগড়াছড়ি', division: 'Chittagong' },
  { id: 'rajshahi', name: 'Rajshahi', name_bn: 'রাজশাহী', division: 'Rajshahi' },
  { id: 'bogra', name: 'Bogra', name_bn: 'বগুড়া', division: 'Rajshahi' },
  { id: 'joypurhat', name: 'Joypurhat', name_bn: 'জয়পুরহাট', division: 'Rajshahi' },
  { id: 'chapainawabganj', name: 'Chapainawabganj', name_bn: 'চাঁপাইনবাবগঞ্জ', division: 'Rajshahi' },
  { id: 'naogaon', name: 'Naogaon', name_bn: 'নওগাঁ', division: 'Rajshahi' },
  { id: 'natore', name: 'Natore', name_bn: 'নাটোর', division: 'Rajshahi' },
  { id: 'pabna', name: 'Pabna', name_bn: 'পাবনা', division: 'Rajshahi' },
  { id: 'sirajganj', name: 'Sirajganj', name_bn: 'সিরাজগঞ্জ', division: 'Rajshahi' },
  { id: 'khulna', name: 'Khulna', name_bn: 'খুলনা', division: 'Khulna' },
  { id: 'jessore', name: 'Jessore', name_bn: 'যশোর', division: 'Khulna' },
  { id: 'satkhira', name: 'Satkhira', name_bn: 'সাতক্ষীরা', division: 'Khulna' },
  { id: 'bagerhat', name: 'Bagerhat', name_bn: 'বাগেরহাট', division: 'Khulna' },
  { id: 'chuadanga', name: 'Chuadanga', name_bn: 'চুয়াডাঙ্গা', division: 'Khulna' },
  { id: 'jhenaidah', name: 'Jhenaidah', name_bn: 'ঝিনাইদহ', division: 'Khulna' },
  { id: 'kushtia', name: 'Kushtia', name_bn: 'কুষ্টিয়া', division: 'Khulna' },
  { id: 'magura', name: 'Magura', name_bn: 'মাগুরা', division: 'Khulna' },
  { id: 'meherpur', name: 'Meherpur', name_bn: 'মেহেরপুর', division: 'Khulna' },
  { id: 'narail', name: 'Narail', name_bn: 'নড়াইল', division: 'Khulna' },
  { id: 'sylhet', name: 'Sylhet', name_bn: 'সিলেট', division: 'Sylhet' },
  { id: 'moulvibazar', name: 'Moulvibazar', name_bn: 'মৌলভীবাজার', division: 'Sylhet' },
  { id: 'habiganj', name: 'Habiganj', name_bn: 'হবিগঞ্জ', division: 'Sylhet' },
  { id: 'sunamganj', name: 'Sunamganj', name_bn: 'সুনামগঞ্জ', division: 'Sylhet' },
  { id: 'barisal', name: 'Barisal', name_bn: 'বরিশাল', division: 'Barisal' },
  { id: 'patuakhali', name: 'Patuakhali', name_bn: 'পটুয়াখালী', division: 'Barisal' },
  { id: 'barguna', name: 'Barguna', name_bn: 'বরগুনা', division: 'Barisal' },
  { id: 'bhola', name: 'Bhola', name_bn: 'ভোলা', division: 'Barisal' },
  { id: 'jhalokati', name: 'Jhalokati', name_bn: 'ঝালকাঠি', division: 'Barisal' },
  { id: 'pirojpur', name: 'Pirojpur', name_bn: 'পিরোজপুর', division: 'Barisal' },
  { id: 'rangpur', name: 'Rangpur', name_bn: 'রংপুর', division: 'Rangpur' },
  { id: 'dinajpur', name: 'Dinajpur', name_bn: 'দিনাজপুর', division: 'Rangpur' },
  { id: 'gaibandha', name: 'Gaibandha', name_bn: 'গাইবান্ধা', division: 'Rangpur' },
  { id: 'kurigram', name: 'Kurigram', name_bn: 'কুড়িগ্রাম', division: 'Rangpur' },
  { id: 'lalmonirhat', name: 'Lalmonirhat', name_bn: 'লালমনিরহাট', division: 'Rangpur' },
  { id: 'nilphamari', name: 'Nilphamari', name_bn: 'নীলফামারী', division: 'Rangpur' },
  { id: 'panchagarh', name: 'Panchagarh', name_bn: 'পঞ্চগড়', division: 'Rangpur' },
  { id: 'thakurgaon', name: 'Thakurgaon', name_bn: 'ঠাকুরগাঁও', division: 'Rangpur' },
  { id: 'mymensingh', name: 'Mymensingh', name_bn: 'ময়মনসিংহ', division: 'Mymensingh' },
  { id: 'jamalpur', name: 'Jamalpur', name_bn: 'জামালপুর', division: 'Mymensingh' },
  { id: 'netrokona', name: 'Netrokona', name_bn: 'নেত্রকোণা', division: 'Mymensingh' },
  { id: 'sherpur', name: 'Sherpur', name_bn: 'শেরপুর', division: 'Mymensingh' },
];

const upazilasByDistrict: Record<string, Upazila[]> = {
  dhaka: [
    { id: 'dhanmondi', district_id: 'dhaka', name: 'Dhanmondi', name_bn: 'ধানমন্ডি' },
    { id: 'mirpur', district_id: 'dhaka', name: 'Mirpur', name_bn: 'মিরপুর' },
    { id: 'uttara', district_id: 'dhaka', name: 'Uttara', name_bn: 'উত্তরা' },
    { id: 'gulshan', district_id: 'dhaka', name: 'Gulshan', name_bn: 'গুলশান' },
    { id: 'motijheel', district_id: 'dhaka', name: 'Motijheel', name_bn: 'মতিঝিল' },
    { id: 'mohammadpur', district_id: 'dhaka', name: 'Mohammadpur', name_bn: 'মোহাম্মদপুর' },
    { id: 'lalbagh', district_id: 'dhaka', name: 'Lalbagh', name_bn: 'লালবাগ' },
    { id: 'demra', district_id: 'dhaka', name: 'Demra', name_bn: 'ডেমরা' },
    { id: 'khilgaon', district_id: 'dhaka', name: 'Khilgaon', name_bn: 'খিলগাঁও' },
    { id: 'badda', district_id: 'dhaka', name: 'Badda', name_bn: 'বাড্ডা' },
    { id: 'rampura', district_id: 'dhaka', name: 'Rampura', name_bn: 'রামপুরা' },
    { id: 'tejgaon', district_id: 'dhaka', name: 'Tejgaon', name_bn: 'তেজগাঁও' },
    { id: 'paltan', district_id: 'dhaka', name: 'Paltan', name_bn: 'পল্টন' },
    { id: 'cantonment', district_id: 'dhaka', name: 'Cantonment', name_bn: 'ক্যান্টনমেন্ট' },
    { id: 'keraniganj', district_id: 'dhaka', name: 'Keraniganj', name_bn: 'কেরানীগঞ্জ' },
    { id: 'dohar', district_id: 'dhaka', name: 'Dohar', name_bn: 'দোহার' },
    { id: 'nawabganj', district_id: 'dhaka', name: 'Nawabganj', name_bn: 'নবাবগঞ্জ' },
    { id: 'savar', district_id: 'dhaka', name: 'Savar', name_bn: 'সাভার' },
  ],
  gazipur: [
    { id: 'gazipur_sadar', district_id: 'gazipur', name: 'Gazipur Sadar', name_bn: 'গাজীপুর সদর' },
    { id: 'tongi', district_id: 'gazipur', name: 'Tongi', name_bn: 'টঙ্গী' },
    { id: 'kaliakoir', district_id: 'gazipur', name: 'Kaliakoir', name_bn: 'কালিয়াকৈর' },
    { id: 'kapasia', district_id: 'gazipur', name: 'Kapasia', name_bn: 'কাপাসিয়া' },
    { id: 'sreepur', district_id: 'gazipur', name: 'Sreepur', name_bn: 'শ্রীপুর' },
    { id: 'kaliganj_gz', district_id: 'gazipur', name: 'Kaliganj', name_bn: 'কালীগঞ্জ' },
  ],
  narayanganj: [
    { id: 'nj_sadar', district_id: 'narayanganj', name: 'Narayanganj Sadar', name_bn: 'নারায়ণগঞ্জ সদর' },
    { id: 'rupganj', district_id: 'narayanganj', name: 'Rupganj', name_bn: 'রূপগঞ্জ' },
    { id: 'araihazar', district_id: 'narayanganj', name: 'Araihazar', name_bn: 'আড়াইহাজার' },
    { id: 'sonargaon', district_id: 'narayanganj', name: 'Sonargaon', name_bn: 'সোনারগাঁও' },
    { id: 'bandor', district_id: 'narayanganj', name: 'Bandor', name_bn: 'বন্দর' },
  ],
  narsingdi: [
    { id: 'narsingdi_sadar', district_id: 'narsingdi', name: 'Narsingdi Sadar', name_bn: 'নরসিংদী সদর' },
    { id: 'belabo', district_id: 'narsingdi', name: 'Belabo', name_bn: 'বেলাব' },
    { id: 'monohardi', district_id: 'narsingdi', name: 'Monohardi', name_bn: 'মনোহরদী' },
    { id: 'palash', district_id: 'narsingdi', name: 'Palash', name_bn: 'পলাশ' },
    { id: 'raipura', district_id: 'narsingdi', name: 'Raipura', name_bn: 'রায়পুরা' },
    { id: 'shibpur', district_id: 'narsingdi', name: 'Shibpur', name_bn: 'শিবপুর' },
  ],
  manikganj: [
    { id: 'manikganj_sadar', district_id: 'manikganj', name: 'Manikganj Sadar', name_bn: 'মানিকগঞ্জ সদর' },
    { id: 'daulatpur', district_id: 'manikganj', name: 'Daulatpur', name_bn: 'দৌলতপুর' },
    { id: 'ghior', district_id: 'manikganj', name: 'Ghior', name_bn: 'ঘিওর' },
    { id: 'harirampur', district_id: 'manikganj', name: 'Harirampur', name_bn: 'হরিরামপুর' },
    { id: 'saturia', district_id: 'manikganj', name: 'Saturia', name_bn: 'সাটুরিয়া' },
    { id: 'shivalaya', district_id: 'manikganj', name: 'Shivalaya', name_bn: 'শিবালয়' },
    { id: 'singair', district_id: 'manikganj', name: 'Singair', name_bn: 'সিংগাইর' },
  ],
  munshiganj: [
    { id: 'munshiganj_sadar', district_id: 'munshiganj', name: 'Munshiganj Sadar', name_bn: 'মুন্সীগঞ্জ সদর' },
    { id: 'gazaria', district_id: 'munshiganj', name: 'Gazaria', name_bn: 'গজারিয়া' },
    { id: 'lohajang', district_id: 'munshiganj', name: 'Lohajang', name_bn: 'লোহাজং' },
    { id: 'sirajdikhan', district_id: 'munshiganj', name: 'Sirajdikhan', name_bn: 'সিরাজদিখান' },
    { id: 'sreenagar', district_id: 'munshiganj', name: 'Sreenagar', name_bn: 'শ্রীনগর' },
    { id: 'tongibari', district_id: 'munshiganj', name: 'Tongibari', name_bn: 'টঙ্গীবাড়ী' },
  ],
  madaripur: [
    { id: 'madaripur_sadar', district_id: 'madaripur', name: 'Madaripur Sadar', name_bn: 'মাদারীপুর সদর' },
    { id: 'kalkini', district_id: 'madaripur', name: 'Kalkini', name_bn: 'কালকিনি' },
    { id: 'rajoir', district_id: 'madaripur', name: 'Rajoir', name_bn: 'রাজৈর' },
    { id: 'shibchar', district_id: 'madaripur', name: 'Shibchar', name_bn: 'শিবচর' },
  ],
  shariatpur: [
    { id: 'shariatpur_sadar', district_id: 'shariatpur', name: 'Shariatpur Sadar', name_bn: 'শরীয়তপুর সদর' },
    { id: 'bhedarganj', district_id: 'shariatpur', name: 'Bhedarganj', name_bn: 'ভেদরগঞ্জ' },
    { id: 'damudya', district_id: 'shariatpur', name: 'Damudya', name_bn: 'ডামুড্যা' },
    { id: 'gosairhat', district_id: 'shariatpur', name: 'Gosairhat', name_bn: 'গোসাইরহাট' },
    { id: 'naria', district_id: 'shariatpur', name: 'Naria', name_bn: 'নড়িয়া' },
    { id: 'zanjira', district_id: 'shariatpur', name: 'Zanjira', name_bn: 'জাজিরা' },
  ],
  faridpur: [
    { id: 'faridpur_sadar', district_id: 'faridpur', name: 'Faridpur Sadar', name_bn: 'ফরিদপুর সদর' },
    { id: 'alfadanga', district_id: 'faridpur', name: 'Alfadanga', name_bn: 'আলফাডাঙ্গা' },
    { id: 'bhanga', district_id: 'faridpur', name: 'Bhanga', name_bn: 'ভাঙ্গা' },
    { id: 'boalmari', district_id: 'faridpur', name: 'Boalmari', name_bn: 'বোয়ালমারী' },
    { id: 'charbhadrasan', district_id: 'faridpur', name: 'Charbhadrasan', name_bn: 'চরভদ্রাসন' },
    { id: 'madhukhali', district_id: 'faridpur', name: 'Madhukhali', name_bn: 'মধুখালী' },
    { id: 'nagarkanda', district_id: 'faridpur', name: 'Nagarkanda', name_bn: 'নগরকান্দা' },
    { id: 'sadarpur', district_id: 'faridpur', name: 'Sadarpur', name_bn: 'সদরপুর' },
    { id: 'saltha', district_id: 'faridpur', name: 'Saltha', name_bn: 'সালথা' },
  ],
  gopalganj: [
    { id: 'gopalganj_sadar', district_id: 'gopalganj', name: 'Gopalganj Sadar', name_bn: 'গোপালগঞ্জ সদর' },
    { id: 'kashiani', district_id: 'gopalganj', name: 'Kashiani', name_bn: 'কাশিয়ানী' },
    { id: 'kotalipara', district_id: 'gopalganj', name: 'Kotalipara', name_bn: 'কোটালীপাড়া' },
    { id: 'muksudpur', district_id: 'gopalganj', name: 'Muksudpur', name_bn: 'মুকসুদপুর' },
    { id: 'tungipara', district_id: 'gopalganj', name: 'Tungipara', name_bn: 'টুঙ্গিপাড়া' },
  ],
  kishoreganj: [
    { id: 'kishoreganj_sadar', district_id: 'kishoreganj', name: 'Kishoreganj Sadar', name_bn: 'কিশোরগঞ্জ সদর' },
    { id: 'austagram', district_id: 'kishoreganj', name: 'Austagram', name_bn: 'অষ্টগ্রাম' },
    { id: 'bajitpur', district_id: 'kishoreganj', name: 'Bajitpur', name_bn: 'বাজিতপুর' },
    { id: 'bhairab', district_id: 'kishoreganj', name: 'Bhairab', name_bn: 'ভৈরব' },
    { id: 'hossainpur', district_id: 'kishoreganj', name: 'Hossainpur', name_bn: 'হোসেনপুর' },
    { id: 'itna', district_id: 'kishoreganj', name: 'Itna', name_bn: 'ইটনা' },
    { id: 'karimganj', district_id: 'kishoreganj', name: 'Karimganj', name_bn: 'করিমগঞ্জ' },
    { id: 'katiadi', district_id: 'kishoreganj', name: 'Katiadi', name_bn: 'কটিয়াদী' },
    { id: 'kuliarchar', district_id: 'kishoreganj', name: 'Kuliarchar', name_bn: 'কুলিয়ারচর' },
    { id: 'mithamain', district_id: 'kishoreganj', name: 'Mithamain', name_bn: 'মিঠামইন' },
    { id: 'nikli', district_id: 'kishoreganj', name: 'Nikli', name_bn: 'নিকলী' },
    { id: 'pakundia', district_id: 'kishoreganj', name: 'Pakundia', name_bn: 'পাকুন্দিয়া' },
    { id: 'tarail', district_id: 'kishoreganj', name: 'Tarail', name_bn: 'তাড়াইল' },
  ],
  tangail: [
    { id: 'tangail_sadar', district_id: 'tangail', name: 'Tangail Sadar', name_bn: 'টাঙ্গাইল সদর' },
    { id: 'basail', district_id: 'tangail', name: 'Basail', name_bn: 'বাসাইল' },
    { id: 'bhuapur', district_id: 'tangail', name: 'Bhuapur', name_bn: 'ভুয়াপুর' },
    { id: 'delduar', district_id: 'tangail', name: 'Delduar', name_bn: 'দেলদুয়ার' },
    { id: 'ghatail', district_id: 'tangail', name: 'Ghatail', name_bn: 'ঘাটাইল' },
    { id: 'gopalpur', district_id: 'tangail', name: 'Gopalpur', name_bn: 'গোপালপুর' },
    { id: 'kalihati', district_id: 'tangail', name: 'Kalihati', name_bn: 'কালিহাতী' },
    { id: 'madhupur', district_id: 'tangail', name: 'Madhupur', name_bn: 'মধুপুর' },
    { id: 'mirzapur', district_id: 'tangail', name: 'Mirzapur', name_bn: 'মির্জাপুর' },
    { id: 'nagarpur', district_id: 'tangail', name: 'Nagarpur', name_bn: 'নাগরপুর' },
    { id: 'sakhipur', district_id: 'tangail', name: 'Sakhipur', name_bn: 'সখিপুর' },
  ],
  chittagong: [
    { id: 'ctg_kotwali', district_id: 'chittagong', name: 'Kotwali', name_bn: 'কোতোয়ালি' },
    { id: 'ctg_pahartali', district_id: 'chittagong', name: 'Pahartali', name_bn: 'পাহাড়তলী' },
    { id: 'ctg_hathazari', district_id: 'chittagong', name: 'Hathazari', name_bn: 'হাটহাজারী' },
    { id: 'ctg_sitakunda', district_id: 'chittagong', name: 'Sitakunda', name_bn: 'সীতাকুণ্ড' },
    { id: 'ctg_anwara', district_id: 'chittagong', name: 'Anwara', name_bn: 'আনোয়ারা' },
    { id: 'ctg_boalkhali', district_id: 'chittagong', name: 'Boalkhali', name_bn: 'বোয়ালখালী' },
    { id: 'ctg_chandanaish', district_id: 'chittagong', name: 'Chandanaish', name_bn: 'চন্দনাইশ' },
    { id: 'ctg_fatikchhari', district_id: 'chittagong', name: 'Fatikchhari', name_bn: 'ফটিকছড়ি' },
    { id: 'ctg_lohagara', district_id: 'chittagong', name: 'Lohagara', name_bn: 'লোহাগাড়া' },
    { id: 'ctg_mirsharai', district_id: 'chittagong', name: 'Mirsharai', name_bn: 'মীরসরাই' },
    { id: 'ctg_patiya', district_id: 'chittagong', name: 'Patiya', name_bn: 'পটিয়া' },
    { id: 'ctg_rangunia', district_id: 'chittagong', name: 'Rangunia', name_bn: 'রাঙ্গুনিয়া' },
    { id: 'ctg_raozan', district_id: 'chittagong', name: 'Raozan', name_bn: 'রাউজান' },
    { id: 'ctg_sandwip', district_id: 'chittagong', name: 'Sandwip', name_bn: 'সন্দ্বীপ' },
    { id: 'ctg_satkania', district_id: 'chittagong', name: 'Satkania', name_bn: 'সাতকানিয়া' },
  ],
  comilla: [
    { id: 'comilla_sadar', district_id: 'comilla', name: 'Comilla Sadar', name_bn: 'কুমিল্লা সদর' },
    { id: 'barura', district_id: 'comilla', name: 'Barura', name_bn: 'বরুড়া' },
    { id: 'brahmanpara', district_id: 'comilla', name: 'Brahmanpara', name_bn: 'ব্রাহ্মণপাড়া' },
    { id: 'burichang', district_id: 'comilla', name: 'Burichang', name_bn: 'বুড়িচং' },
    { id: 'chandina', district_id: 'comilla', name: 'Chandina', name_bn: 'চান্দিনা' },
    { id: 'chauddagram', district_id: 'comilla', name: 'Chauddagram', name_bn: 'চৌদ্দগ্রাম' },
    { id: 'daudkandi', district_id: 'comilla', name: 'Daudkandi', name_bn: 'দাউদকান্দি' },
    { id: 'debidwar', district_id: 'comilla', name: 'Debidwar', name_bn: 'দেবিদ্বার' },
    { id: 'homna', district_id: 'comilla', name: 'Homna', name_bn: 'হোমনা' },
    { id: 'laksam', district_id: 'comilla', name: 'Laksam', name_bn: 'লাকসাম' },
    { id: 'meghna', district_id: 'comilla', name: 'Meghna', name_bn: 'মেঘনা' },
    { id: 'monohorgonj', district_id: 'comilla', name: 'Monohorgonj', name_bn: 'মনোহরগঞ্জ' },
    { id: 'muradnagar', district_id: 'comilla', name: 'Muradnagar', name_bn: 'মুরাদনগর' },
    { id: 'nangalkot', district_id: 'comilla', name: 'Nangalkot', name_bn: 'নাঙ্গলকোট' },
    { id: 'titas', district_id: 'comilla', name: 'Titas', name_bn: 'তিতাস' },
  ],
  feni: [
    { id: 'feni_sadar', district_id: 'feni', name: 'Feni Sadar', name_bn: 'ফেনী সদর' },
    { id: 'chhagalnaiya', district_id: 'feni', name: 'Chhagalnaiya', name_bn: 'ছাগলনাইয়া' },
    { id: 'daganbhuiyan', district_id: 'feni', name: 'Daganbhuiyan', name_bn: 'দাগনভূঁইয়া' },
    { id: 'parshuram', district_id: 'feni', name: 'Parshuram', name_bn: 'পরশুরাম' },
    { id: 'sonagazi', district_id: 'feni', name: 'Sonagazi', name_bn: 'সোনাগাজী' },
  ],
  brahmanbaria: [
    { id: 'brahmanbaria_sadar', district_id: 'brahmanbaria', name: 'Brahmanbaria Sadar', name_bn: 'ব্রাহ্মণবাড়িয়া সদর' },
    { id: 'akhaura', district_id: 'brahmanbaria', name: 'Akhaura', name_bn: 'আখাউড়া' },
    { id: 'ashuganj', district_id: 'brahmanbaria', name: 'Ashuganj', name_bn: 'আশুগঞ্জ' },
    { id: 'bancharampur', district_id: 'brahmanbaria', name: 'Bancharampur', name_bn: 'বাঞ্ছারামপুর' },
    { id: 'bijoynagar', district_id: 'brahmanbaria', name: 'Bijoynagar', name_bn: 'বিজয়নগর' },
    { id: 'kasba', district_id: 'brahmanbaria', name: 'Kasba', name_bn: 'কসবা' },
    { id: 'nabinagar', district_id: 'brahmanbaria', name: 'Nabinagar', name_bn: 'নবীনগর' },
    { id: 'nasirnagar', district_id: 'brahmanbaria', name: 'Nasirnagar', name_bn: 'নাসিরনগর' },
    { id: 'sarail', district_id: 'brahmanbaria', name: 'Sarail', name_bn: 'সরাইল' },
  ],
  chandpur: [
    { id: 'chandpur_sadar', district_id: 'chandpur', name: 'Chandpur Sadar', name_bn: 'চাঁদপুর সদর' },
    { id: 'faridganj', district_id: 'chandpur', name: 'Faridganj', name_bn: 'ফরিদগঞ্জ' },
    { id: 'haimchar', district_id: 'chandpur', name: 'Haimchar', name_bn: 'হাইমচর' },
    { id: 'haziganj', district_id: 'chandpur', name: 'Haziganj', name_bn: 'হাজীগঞ্জ' },
    { id: 'kachua', district_id: 'chandpur', name: 'Kachua', name_bn: 'কচুয়া' },
    { id: 'matlab_north', district_id: 'chandpur', name: 'Matlab North', name_bn: 'মতলব উত্তর' },
    { id: 'matlab_south', district_id: 'chandpur', name: 'Matlab South', name_bn: 'মতলব দক্ষিণ' },
    { id: 'shahrasti', district_id: 'chandpur', name: 'Shahrasti', name_bn: 'শাহরাস্তি' },
  ],
  lakshmipur: [
    { id: 'lakshmipur_sadar', district_id: 'lakshmipur', name: 'Lakshmipur Sadar', name_bn: 'লক্ষ্মীপুর সদর' },
    { id: 'kamalnagar', district_id: 'lakshmipur', name: 'Kamalnagar', name_bn: 'কমলনগর' },
    { id: 'raipur', district_id: 'lakshmipur', name: 'Raipur', name_bn: 'রায়পুর' },
    { id: 'ramganj', district_id: 'lakshmipur', name: 'Ramganj', name_bn: 'রামগঞ্জ' },
    { id: 'ramgati', district_id: 'lakshmipur', name: 'Ramgati', name_bn: 'রামগতি' },
  ],
  noakhali: [
    { id: 'noakhali_sadar', district_id: 'noakhali', name: 'Noakhali Sadar', name_bn: 'নোয়াখালী সদর' },
    { id: 'begumganj', district_id: 'noakhali', name: 'Begumganj', name_bn: 'বেগমগঞ্জ' },
    { id: 'chatkhil', district_id: 'noakhali', name: 'Chatkhil', name_bn: 'চাটখিল' },
    { id: 'companiganj', district_id: 'noakhali', name: 'Companiganj', name_bn: 'কোম্পানীগঞ্জ' },
    { id: 'hatiya', district_id: 'noakhali', name: 'Hatiya', name_bn: 'হাতিয়া' },
    { id: 'kabirhat', district_id: 'noakhali', name: 'Kabirhat', name_bn: 'কবিরহাট' },
    { id: 'senbagh', district_id: 'noakhali', name: 'Senbagh', name_bn: 'সেনবাগ' },
    { id: 'sonaimuri', district_id: 'noakhali', name: 'Sonaimuri', name_bn: 'সোনাইমুড়ী' },
    { id: 'subarnachar', district_id: 'noakhali', name: 'Subarnachar', name_bn: 'সুবর্ণচর' },
  ],
  cox_bazar: [
    { id: 'cox_sadar', district_id: 'cox_bazar', name: "Cox's Bazar Sadar", name_bn: 'কক্সবাজার সদর' },
    { id: 'chakaria', district_id: 'cox_bazar', name: 'Chakaria', name_bn: 'চকরিয়া' },
    { id: 'kutubdia', district_id: 'cox_bazar', name: 'Kutubdia', name_bn: 'কুতুবদিয়া' },
    { id: 'maheshkhali', district_id: 'cox_bazar', name: 'Maheshkhali', name_bn: 'মহেশখালী' },
    { id: 'pekua', district_id: 'cox_bazar', name: 'Pekua', name_bn: 'পেকুয়া' },
    { id: 'ramu', district_id: 'cox_bazar', name: 'Ramu', name_bn: 'রামু' },
    { id: 'teknaf', district_id: 'cox_bazar', name: 'Teknaf', name_bn: 'টেকনাফ' },
    { id: 'ukhia', district_id: 'cox_bazar', name: 'Ukhia', name_bn: 'উখিয়া' },
  ],
  rangamati: [
    { id: 'rangamati_sadar', district_id: 'rangamati', name: 'Rangamati Sadar', name_bn: 'রাঙ্গামাটি সদর' },
    { id: 'bagaichhari', district_id: 'rangamati', name: 'Bagaichhari', name_bn: 'বাঘাইছড়ি' },
    { id: 'barkal', district_id: 'rangamati', name: 'Barkal', name_bn: 'বরকল' },
    { id: 'belaichhari', district_id: 'rangamati', name: 'Belaichhari', name_bn: 'বিলাইছড়ি' },
    { id: 'juraichhari', district_id: 'rangamati', name: 'Juraichhari', name_bn: 'জুরাছড়ি' },
    { id: 'kaptai', district_id: 'rangamati', name: 'Kaptai', name_bn: 'কাপ্তাই' },
    { id: 'kawkhali', district_id: 'rangamati', name: 'Kawkhali', name_bn: 'কাউখালী' },
    { id: 'langadu', district_id: 'rangamati', name: 'Langadu', name_bn: 'লংগদু' },
    { id: 'nannerchar', district_id: 'rangamati', name: 'Nannerchar', name_bn: 'নানিয়ারচর' },
    { id: 'rajasthali', district_id: 'rangamati', name: 'Rajasthali', name_bn: 'রাজস্থলী' },
  ],
  bandarban: [
    { id: 'bandarban_sadar', district_id: 'bandarban', name: 'Bandarban Sadar', name_bn: 'বান্দরবান সদর' },
    { id: 'alikadam', district_id: 'bandarban', name: 'Alikadam', name_bn: 'আলীকদম' },
    { id: 'lama', district_id: 'bandarban', name: 'Lama', name_bn: 'লামা' },
    { id: 'naikhongchhari', district_id: 'bandarban', name: 'Naikhongchhari', name_bn: 'নাইক্ষ্যংছড়ি' },
    { id: 'rowangchhari', district_id: 'bandarban', name: 'Rowangchhari', name_bn: 'রোয়াংছড়ি' },
    { id: 'ruma', district_id: 'bandarban', name: 'Ruma', name_bn: 'রুমা' },
    { id: 'thanchi', district_id: 'bandarban', name: 'Thanchi', name_bn: 'থানচি' },
  ],
  khagrachhari: [
    { id: 'khagrachhari_sadar', district_id: 'khagrachhari', name: 'Khagrachhari Sadar', name_bn: 'খাগড়াছড়ি সদর' },
    { id: 'dighinala', district_id: 'khagrachhari', name: 'Dighinala', name_bn: 'দিঘীনালা' },
    { id: 'lakshmichhari', district_id: 'khagrachhari', name: 'Lakshmichhari', name_bn: 'লক্ষ্মীছড়ি' },
    { id: 'mahalchhari', district_id: 'khagrachhari', name: 'Mahalchhari', name_bn: 'মহালছড়ি' },
    { id: 'manikchhari', district_id: 'khagrachhari', name: 'Manikchhari', name_bn: 'মানিকছড়ি' },
    { id: 'matiranga', district_id: 'khagrachhari', name: 'Matiranga', name_bn: 'মাটিরাঙ্গা' },
    { id: 'panchhari', district_id: 'khagrachhari', name: 'Panchhari', name_bn: 'পানছড়ি' },
    { id: 'ramgarh', district_id: 'khagrachhari', name: 'Ramgarh', name_bn: 'রামগড়' },
  ],
  rajshahi: [
    { id: 'rajshahi_sadar', district_id: 'rajshahi', name: 'Rajshahi Sadar', name_bn: 'রাজশাহী সদর' },
    { id: 'bagha', district_id: 'rajshahi', name: 'Bagha', name_bn: 'বাঘা' },
    { id: 'bagmara', district_id: 'rajshahi', name: 'Bagmara', name_bn: 'বাগমারা' },
    { id: 'charghat', district_id: 'rajshahi', name: 'Charghat', name_bn: 'চারঘাট' },
    { id: 'durgapur', district_id: 'rajshahi', name: 'Durgapur', name_bn: 'দুর্গাপুর' },
    { id: 'godagari', district_id: 'rajshahi', name: 'Godagari', name_bn: 'গোদাগাড়ী' },
    { id: 'mohanpur', district_id: 'rajshahi', name: 'Mohanpur', name_bn: 'মোহনপুর' },
    { id: 'paba', district_id: 'rajshahi', name: 'Paba', name_bn: 'পবা' },
    { id: 'putia', district_id: 'rajshahi', name: 'Putia', name_bn: 'পুঠিয়া' },
    { id: 'tanore', district_id: 'rajshahi', name: 'Tanore', name_bn: 'তানোর' },
  ],
  bogra: [
    { id: 'bogra_sadar', district_id: 'bogra', name: 'Bogra Sadar', name_bn: 'বগুড়া সদর' },
    { id: 'adamdighi', district_id: 'bogra', name: 'Adamdighi', name_bn: 'আদমদীঘি' },
    { id: 'bogra_dhunat', district_id: 'bogra', name: 'Dhunat', name_bn: 'ধুনট' },
    { id: 'dupchanchiya', district_id: 'bogra', name: 'Dupchanchiya', name_bn: 'দুপচাঁচিয়া' },
    { id: 'gabtali', district_id: 'bogra', name: 'Gabtali', name_bn: 'গাবতলী' },
    { id: 'kahaloo', district_id: 'bogra', name: 'Kahaloo', name_bn: 'কাহালু' },
    { id: 'nandigram', district_id: 'bogra', name: 'Nandigram', name_bn: 'নন্দীগ্রাম' },
    { id: 'sariakandi', district_id: 'bogra', name: 'Sariakandi', name_bn: 'সারিয়াকান্দি' },
    { id: 'shajahanpur', district_id: 'bogra', name: 'Shajahanpur', name_bn: 'শাজাহানপুর' },
    { id: 'sherpur_bogra', district_id: 'bogra', name: 'Sherpur', name_bn: 'শেরপুর' },
    { id: 'shibganj', district_id: 'bogra', name: 'Shibganj', name_bn: 'শিবগঞ্জ' },
    { id: 'sonatala', district_id: 'bogra', name: 'Sonatala', name_bn: 'সোনাতলা' },
  ],
  joypurhat: [
    { id: 'joypurhat_sadar', district_id: 'joypurhat', name: 'Joypurhat Sadar', name_bn: 'জয়পুরহাট সদর' },
    { id: 'akkelpur', district_id: 'joypurhat', name: 'Akkelpur', name_bn: 'আক্কেলপুর' },
    { id: 'kalai', district_id: 'joypurhat', name: 'Kalai', name_bn: 'কালাই' },
    { id: 'khetlal', district_id: 'joypurhat', name: 'Khetlal', name_bn: 'ক্ষেতলাল' },
    { id: 'panchbibi', district_id: 'joypurhat', name: 'Panchbibi', name_bn: 'পাঁচবিবি' },
  ],
  chapainawabganj: [
    { id: 'chapai_sadar', district_id: 'chapainawabganj', name: 'Chapainawabganj Sadar', name_bn: 'চাঁপাইনবাবগঞ্জ সদর' },
    { id: 'bholahat', district_id: 'chapainawabganj', name: 'Bholahat', name_bn: 'ভোলাহাট' },
    { id: 'gomastapur', district_id: 'chapainawabganj', name: 'Gomastapur', name_bn: 'গোমস্তাপুর' },
    { id: 'nachole', district_id: 'chapainawabganj', name: 'Nachole', name_bn: 'নাচোল' },
    { id: 'shibganj_ch', district_id: 'chapainawabganj', name: 'Shibganj', name_bn: 'শিবগঞ্জ' },
  ],
  naogaon: [
    { id: 'naogaon_sadar', district_id: 'naogaon', name: 'Naogaon Sadar', name_bn: 'নওগাঁ সদর' },
    { id: 'atrai', district_id: 'naogaon', name: 'Atrai', name_bn: 'আত্রাই' },
    { id: 'badalgachhi', district_id: 'naogaon', name: 'Badalgachhi', name_bn: 'বদলগাছী' },
    { id: 'dhamoirhat', district_id: 'naogaon', name: 'Dhamoirhat', name_bn: 'ধামইরহাট' },
    { id: 'manda', district_id: 'naogaon', name: 'Manda', name_bn: 'মান্দা' },
    { id: 'mahadebpur', district_id: 'naogaon', name: 'Mahadebpur', name_bn: 'মহাদেবপুর' },
    { id: 'niamatpur', district_id: 'naogaon', name: 'Niamatpur', name_bn: 'নিয়ামতপুর' },
    { id: 'patnitala', district_id: 'naogaon', name: 'Patnitala', name_bn: 'পত্নীতলা' },
    { id: 'porsha', district_id: 'naogaon', name: 'Porsha', name_bn: 'পোরশা' },
    { id: 'raninagar', district_id: 'naogaon', name: 'Raninagar', name_bn: 'রানীনগর' },
    { id: 'sapahar', district_id: 'naogaon', name: 'Sapahar', name_bn: 'সাপাহার' },
  ],
  natore: [
    { id: 'natore_sadar', district_id: 'natore', name: 'Natore Sadar', name_bn: 'নাটোর সদর' },
    { id: 'bagatipara', district_id: 'natore', name: 'Bagatipara', name_bn: 'বাগাতিপাড়া' },
    { id: 'baraigram', district_id: 'natore', name: 'Baraigram', name_bn: 'বড়াইগ্রাম' },
    { id: 'gurudaspur', district_id: 'natore', name: 'Gurudaspur', name_bn: 'গুরুদাসপুর' },
    { id: 'lalpur', district_id: 'natore', name: 'Lalpur', name_bn: 'লালপুর' },
    { id: 'singra', district_id: 'natore', name: 'Singra', name_bn: 'সিংড়া' },
  ],
  pabna: [
    { id: 'pabna_sadar', district_id: 'pabna', name: 'Pabna Sadar', name_bn: 'পাবনা সদর' },
    { id: 'atgharia', district_id: 'pabna', name: 'Atgharia', name_bn: 'আটঘরিয়া' },
    { id: 'bera', district_id: 'pabna', name: 'Bera', name_bn: 'বেড়া' },
    { id: 'bhangura', district_id: 'pabna', name: 'Bhangura', name_bn: 'ভাঙ্গুড়া' },
    { id: 'chatmohar', district_id: 'pabna', name: 'Chatmohar', name_bn: 'চাটমোহর' },
    { id: 'faridpur_pabna', district_id: 'pabna', name: 'Faridpur', name_bn: 'ফরিদপুর' },
    { id: 'ishwardi', district_id: 'pabna', name: 'Ishwardi', name_bn: 'ঈশ্বরদী' },
    { id: 'santhia', district_id: 'pabna', name: 'Santhia', name_bn: 'সাঁথিয়া' },
    { id: 'sujanagar', district_id: 'pabna', name: 'Sujanagar', name_bn: 'সুজানগর' },
  ],
  sirajganj: [
    { id: 'sirajganj_sadar', district_id: 'sirajganj', name: 'Sirajganj Sadar', name_bn: 'সিরাজগঞ্জ সদর' },
    { id: 'belkuchi', district_id: 'sirajganj', name: 'Belkuchi', name_bn: 'বেলকুচি' },
    { id: 'chauhali', district_id: 'sirajganj', name: 'Chauhali', name_bn: 'চৌহালী' },
    { id: 'kamarkhanda', district_id: 'sirajganj', name: 'Kamarkhanda', name_bn: 'কামারখন্দ' },
    { id: 'kazipur', district_id: 'sirajganj', name: 'Kazipur', name_bn: 'কাজীপুর' },
    { id: 'raiganj', district_id: 'sirajganj', name: 'Raiganj', name_bn: 'রায়গঞ্জ' },
    { id: 'shahjadpur', district_id: 'sirajganj', name: 'Shahjadpur', name_bn: 'শাহজাদপুর' },
    { id: 'tarash', district_id: 'sirajganj', name: 'Tarash', name_bn: 'তাড়াশ' },
    { id: 'ullahpara', district_id: 'sirajganj', name: 'Ullahpara', name_bn: 'উল্লাপাড়া' },
  ],
  khulna: [
    { id: 'khulna_sadar', district_id: 'khulna', name: 'Khulna Sadar', name_bn: 'খুলনা সদর' },
    { id: 'batiaghata', district_id: 'khulna', name: 'Batiaghata', name_bn: 'বটিয়াঘাটা' },
    { id: 'dacope', district_id: 'khulna', name: 'Dacope', name_bn: 'দাকোপ' },
    { id: 'dumuria', district_id: 'khulna', name: 'Dumuria', name_bn: 'ডুমুরিয়া' },
    { id: 'dighalia', district_id: 'khulna', name: 'Dighalia', name_bn: 'দিঘলিয়া' },
    { id: 'koyra', district_id: 'khulna', name: 'Koyra', name_bn: 'কয়রা' },
    { id: 'paikgachha', district_id: 'khulna', name: 'Paikgachha', name_bn: 'পাইকগাছা' },
    { id: 'phultala', district_id: 'khulna', name: 'Phultala', name_bn: 'ফুলতলা' },
    { id: 'rupsha', district_id: 'khulna', name: 'Rupsha', name_bn: 'রূপসা' },
    { id: 'terokhada', district_id: 'khulna', name: 'Terokhada', name_bn: 'তেরখাদা' },
  ],
  jessore: [
    { id: 'jessore_sadar', district_id: 'jessore', name: 'Jessore Sadar', name_bn: 'যশোর সদর' },
    { id: 'abhaynagar', district_id: 'jessore', name: 'Abhaynagar', name_bn: 'অভয়নগর' },
    { id: 'bagherpara', district_id: 'jessore', name: 'Bagherpara', name_bn: 'বাঘারপাড়া' },
    { id: 'chaugachha', district_id: 'jessore', name: 'Chaugachha', name_bn: 'চৌগাছা' },
    { id: 'jhikargachha', district_id: 'jessore', name: 'Jhikargachha', name_bn: 'ঝিকরগাছা' },
    { id: 'keshabpur', district_id: 'jessore', name: 'Keshabpur', name_bn: 'কেশবপুর' },
    { id: 'manirampur', district_id: 'jessore', name: 'Manirampur', name_bn: 'মণিরামপুর' },
    { id: 'sharsha', district_id: 'jessore', name: 'Sharsha', name_bn: 'শার্শা' },
  ],
  satkhira: [
    { id: 'satkhira_sadar', district_id: 'satkhira', name: 'Satkhira Sadar', name_bn: 'সাতক্ষীরা সদর' },
    { id: 'assasuni', district_id: 'satkhira', name: 'Assasuni', name_bn: 'আশাশুনি' },
    { id: 'debhata', district_id: 'satkhira', name: 'Debhata', name_bn: 'দেবহাটা' },
    { id: 'kalaroa', district_id: 'satkhira', name: 'Kalaroa', name_bn: 'কলারোয়া' },
    { id: 'kaliganj_sk', district_id: 'satkhira', name: 'Kaliganj', name_bn: 'কালিগঞ্জ' },
    { id: 'shyamnagar', district_id: 'satkhira', name: 'Shyamnagar', name_bn: 'শ্যামনগর' },
    { id: 'tala', district_id: 'satkhira', name: 'Tala', name_bn: 'তালা' },
  ],
  bagerhat: [
    { id: 'bagerhat_sadar', district_id: 'bagerhat', name: 'Bagerhat Sadar', name_bn: 'বাগেরহাট সদর' },
    { id: 'chitalmari', district_id: 'bagerhat', name: 'Chitalmari', name_bn: 'চিতলমারী' },
    { id: 'fakirhat', district_id: 'bagerhat', name: 'Fakirhat', name_bn: 'ফকিরহাট' },
    { id: 'kachua_bg', district_id: 'bagerhat', name: 'Kachua', name_bn: 'কচুয়া' },
    { id: 'mollahat', district_id: 'bagerhat', name: 'Mollahat', name_bn: 'মোল্লাহাট' },
    { id: 'mongla', district_id: 'bagerhat', name: 'Mongla', name_bn: 'মোংলা' },
    { id: 'morrelganj', district_id: 'bagerhat', name: 'Morrelganj', name_bn: 'মোড়েলগঞ্জ' },
    { id: 'rampal', district_id: 'bagerhat', name: 'Rampal', name_bn: 'রামপাল' },
    { id: 'sarankhola', district_id: 'bagerhat', name: 'Sarankhola', name_bn: 'শরণখোলা' },
  ],
  chuadanga: [
    { id: 'chuadanga_sadar', district_id: 'chuadanga', name: 'Chuadanga Sadar', name_bn: 'চুয়াডাঙ্গা সদর' },
    { id: 'alamdanga', district_id: 'chuadanga', name: 'Alamdanga', name_bn: 'আলমডাঙ্গা' },
    { id: 'damurhuda', district_id: 'chuadanga', name: 'Damurhuda', name_bn: 'দামুড়হুদা' },
    { id: 'jibannagar', district_id: 'chuadanga', name: 'Jibannagar', name_bn: 'জীবননগর' },
  ],
  jhenaidah: [
    { id: 'jhenaidah_sadar', district_id: 'jhenaidah', name: 'Jhenaidah Sadar', name_bn: 'ঝিনাইদহ সদর' },
    { id: 'harinakunda', district_id: 'jhenaidah', name: 'Harinakunda', name_bn: 'হরিণাকুণ্ডু' },
    { id: 'kaliganj_jh', district_id: 'jhenaidah', name: 'Kaliganj', name_bn: 'কালীগঞ্জ' },
    { id: 'kotchandpur', district_id: 'jhenaidah', name: 'Kotchandpur', name_bn: 'কোটচাঁদপুর' },
    { id: 'maheshpur', district_id: 'jhenaidah', name: 'Maheshpur', name_bn: 'মহেশপুর' },
    { id: 'shailkupa', district_id: 'jhenaidah', name: 'Shailkupa', name_bn: 'শৈলকুপা' },
  ],
  kushtia: [
    { id: 'kushtia_sadar', district_id: 'kushtia', name: 'Kushtia Sadar', name_bn: 'কুষ্টিয়া সদর' },
    { id: 'bheramara', district_id: 'kushtia', name: 'Bheramara', name_bn: 'ভেড়ামারা' },
    { id: 'daulatpur_ku', district_id: 'kushtia', name: 'Daulatpur', name_bn: 'দৌলতপুর' },
    { id: 'khoksa', district_id: 'kushtia', name: 'Khoksa', name_bn: 'খোকসা' },
    { id: 'kumarkhali', district_id: 'kushtia', name: 'Kumarkhali', name_bn: 'কুমারখালী' },
    { id: 'mirpur_ku', district_id: 'kushtia', name: 'Mirpur', name_bn: 'মিরপুর' },
  ],
  magura: [
    { id: 'magura_sadar', district_id: 'magura', name: 'Magura Sadar', name_bn: 'মাগুরা সদর' },
    { id: 'mohammadpur_mg', district_id: 'magura', name: 'Mohammadpur', name_bn: 'মোহাম্মদপুর' },
    { id: 'shalikha', district_id: 'magura', name: 'Shalikha', name_bn: 'শালিখা' },
    { id: 'sreepur_mg', district_id: 'magura', name: 'Sreepur', name_bn: 'শ্রীপুর' },
  ],
  meherpur: [
    { id: 'meherpur_sadar', district_id: 'meherpur', name: 'Meherpur Sadar', name_bn: 'মেহেরপুর সদর' },
    { id: 'gangni', district_id: 'meherpur', name: 'Gangni', name_bn: 'গাংনী' },
    { id: 'mujibnagar', district_id: 'meherpur', name: 'Mujibnagar', name_bn: 'মুজিবনগর' },
  ],
  narail: [
    { id: 'narail_sadar', district_id: 'narail', name: 'Narail Sadar', name_bn: 'নড়াইল সদর' },
    { id: 'kalia', district_id: 'narail', name: 'Kalia', name_bn: 'কালিয়া' },
    { id: 'lohagara_nr', district_id: 'narail', name: 'Lohagara', name_bn: 'লোহাগড়া' },
  ],
  sylhet: [
    { id: 'sylhet_sadar', district_id: 'sylhet', name: 'Sylhet Sadar', name_bn: 'সিলেট সদর' },
    { id: 'balaganj', district_id: 'sylhet', name: 'Balaganj', name_bn: 'বালাগঞ্জ' },
    { id: 'beanibazar', district_id: 'sylhet', name: 'Beanibazar', name_bn: 'বিয়ানীবাজার' },
    { id: 'bishwanath', district_id: 'sylhet', name: 'Bishwanath', name_bn: 'বিশ্বনাথ' },
    { id: 'companiganj_sy', district_id: 'sylhet', name: 'Companiganj', name_bn: 'কোম্পানীগঞ্জ' },
    { id: 'fenchuganj', district_id: 'sylhet', name: 'Fenchuganj', name_bn: 'ফেঞ্চুগঞ্জ' },
    { id: 'golapganj', district_id: 'sylhet', name: 'Golapganj', name_bn: 'গোলাপগঞ্জ' },
    { id: 'gowainghat', district_id: 'sylhet', name: 'Gowainghat', name_bn: 'গোয়াইনঘাট' },
    { id: 'jaintiapur', district_id: 'sylhet', name: 'Jaintiapur', name_bn: 'জৈন্তাপুর' },
    { id: 'kanaighat', district_id: 'sylhet', name: 'Kanaighat', name_bn: 'কানাইঘাট' },
    { id: 'osmani_nagar', district_id: 'sylhet', name: 'Osmaninagar', name_bn: 'ওসমানীনগর' },
    { id: 'south_surma', district_id: 'sylhet', name: 'South Surma', name_bn: 'দক্ষিণ সুরমা' },
  ],
  moulvibazar: [
    { id: 'moulvibazar_sadar', district_id: 'moulvibazar', name: 'Moulvibazar Sadar', name_bn: 'মৌলভীবাজার সদর' },
    { id: 'barlekha', district_id: 'moulvibazar', name: 'Barlekha', name_bn: 'বড়লেখা' },
    { id: 'juri', district_id: 'moulvibazar', name: 'Juri', name_bn: 'জুড়ী' },
    { id: 'kamalganj', district_id: 'moulvibazar', name: 'Kamalganj', name_bn: 'কমলগঞ্জ' },
    { id: 'kulaura', district_id: 'moulvibazar', name: 'Kulaura', name_bn: 'কুলাউড়া' },
    { id: 'rajnagar', district_id: 'moulvibazar', name: 'Rajnagar', name_bn: 'রাজনগর' },
    { id: 'sreemangal', district_id: 'moulvibazar', name: 'Sreemangal', name_bn: 'শ্রীমঙ্গল' },
  ],
  habiganj: [
    { id: 'habiganj_sadar', district_id: 'habiganj', name: 'Habiganj Sadar', name_bn: 'হবিগঞ্জ সদর' },
    { id: 'ajmiriganj', district_id: 'habiganj', name: 'Ajmiriganj', name_bn: 'আজমিরীগঞ্জ' },
    { id: 'bahubal', district_id: 'habiganj', name: 'Bahubal', name_bn: 'বাহুবল' },
    { id: 'baniyachong', district_id: 'habiganj', name: 'Baniyachong', name_bn: 'বানিয়াচং' },
    { id: 'chunarughat', district_id: 'habiganj', name: 'Chunarughat', name_bn: 'চুনারুঘাট' },
    { id: 'lakhai', district_id: 'habiganj', name: 'Lakhai', name_bn: 'লাখাই' },
    { id: 'madhabpur', district_id: 'habiganj', name: 'Madhabpur', name_bn: 'মাধবপুর' },
    { id: 'nabiganj', district_id: 'habiganj', name: 'Nabiganj', name_bn: 'নবীগঞ্জ' },
  ],
  sunamganj: [
    { id: 'sunamganj_sadar', district_id: 'sunamganj', name: 'Sunamganj Sadar', name_bn: 'সুনামগঞ্জ সদর' },
    { id: 'bishwambarpur', district_id: 'sunamganj', name: 'Bishwambarpur', name_bn: 'বিশ্বম্ভরপুর' },
    { id: 'chhatak', district_id: 'sunamganj', name: 'Chhatak', name_bn: 'ছাতক' },
    { id: 'derai', district_id: 'sunamganj', name: 'Derai', name_bn: 'দেরাই' },
    { id: 'dharampasha', district_id: 'sunamganj', name: 'Dharampasha', name_bn: 'ধর্মপাশা' },
    { id: 'dowarabazar', district_id: 'sunamganj', name: 'Dowarabazar', name_bn: 'দোয়ারাবাজার' },
    { id: 'jagannathpur', district_id: 'sunamganj', name: 'Jagannathpur', name_bn: 'জগন্নাথপুর' },
    { id: 'jamalganj', district_id: 'sunamganj', name: 'Jamalganj', name_bn: 'জামালগঞ্জ' },
    { id: 'sullah', district_id: 'sunamganj', name: 'Sullah', name_bn: 'সুল্লা' },
    { id: 'tahirpur', district_id: 'sunamganj', name: 'Tahirpur', name_bn: 'তাহিরপুর' },
  ],
  barisal: [
    { id: 'barisal_sadar', district_id: 'barisal', name: 'Barisal Sadar', name_bn: 'বরিশাল সদর' },
    { id: 'agailjhara', district_id: 'barisal', name: 'Agailjhara', name_bn: 'আগৈলঝাড়া' },
    { id: 'babuganj', district_id: 'barisal', name: 'Babuganj', name_bn: 'বাবুগঞ্জ' },
    { id: 'bakerganj', district_id: 'barisal', name: 'Bakerganj', name_bn: 'বাকেরগঞ্জ' },
    { id: 'banaripara', district_id: 'barisal', name: 'Banaripara', name_bn: 'বানারীপাড়া' },
    { id: 'gaurnadi', district_id: 'barisal', name: 'Gaurnadi', name_bn: 'গৌরনদী' },
    { id: 'hizla', district_id: 'barisal', name: 'Hizla', name_bn: 'হিজলা' },
    { id: 'mehendiganj', district_id: 'barisal', name: 'Mehendiganj', name_bn: 'মেহেন্দিগঞ্জ' },
    { id: 'muladi', district_id: 'barisal', name: 'Muladi', name_bn: 'মুলাদী' },
    { id: 'wazirpur', district_id: 'barisal', name: 'Wazirpur', name_bn: 'উজিরপুর' },
  ],
  patuakhali: [
    { id: 'patuakhali_sadar', district_id: 'patuakhali', name: 'Patuakhali Sadar', name_bn: 'পটুয়াখালী সদর' },
    { id: 'bauphal', district_id: 'patuakhali', name: 'Bauphal', name_bn: 'বাউফল' },
    { id: 'dashmina', district_id: 'patuakhali', name: 'Dashmina', name_bn: 'দশমিনা' },
    { id: 'dumki', district_id: 'patuakhali', name: 'Dumki', name_bn: 'দুমকি' },
    { id: 'galachipa', district_id: 'patuakhali', name: 'Galachipa', name_bn: 'গলাচিপা' },
    { id: 'kalapara', district_id: 'patuakhali', name: 'Kalapara', name_bn: 'কলাপাড়া' },
    { id: 'mirzaganj', district_id: 'patuakhali', name: 'Mirzaganj', name_bn: 'মির্জাগঞ্জ' },
    { id: 'rangabali', district_id: 'patuakhali', name: 'Rangabali', name_bn: 'রাঙ্গাবালী' },
  ],
  barguna: [
    { id: 'barguna_sadar', district_id: 'barguna', name: 'Barguna Sadar', name_bn: 'বরগুনা সদর' },
    { id: 'amtali', district_id: 'barguna', name: 'Amtali', name_bn: 'আমতলী' },
    { id: 'bamna', district_id: 'barguna', name: 'Bamna', name_bn: 'বামনা' },
    { id: 'betagi', district_id: 'barguna', name: 'Betagi', name_bn: 'বেতাগী' },
    { id: 'pathorghata', district_id: 'barguna', name: 'Pathorghata', name_bn: 'পাথরঘাটা' },
    { id: 'taltali', district_id: 'barguna', name: 'Taltali', name_bn: 'তালতলী' },
  ],
  bhola: [
    { id: 'bhola_sadar', district_id: 'bhola', name: 'Bhola Sadar', name_bn: 'ভোলা সদর' },
    { id: 'burhanuddin', district_id: 'bhola', name: 'Burhanuddin', name_bn: 'বোরহানউদ্দিন' },
    { id: 'char_fasson', district_id: 'bhola', name: 'Char Fasson', name_bn: 'চরফ্যাশন' },
    { id: 'daulatkhan', district_id: 'bhola', name: 'Daulatkhan', name_bn: 'দৌলতখান' },
    { id: 'lalmohan', district_id: 'bhola', name: 'Lalmohan', name_bn: 'লালমোহন' },
    { id: 'manpura', district_id: 'bhola', name: 'Manpura', name_bn: 'মনপুরা' },
    { id: 'tazumuddin', district_id: 'bhola', name: 'Tazumuddin', name_bn: 'তজুমদ্দিন' },
  ],
  jhalokati: [
    { id: 'jhalokati_sadar', district_id: 'jhalokati', name: 'Jhalokati Sadar', name_bn: 'ঝালকাঠি সদর' },
    { id: 'kathalia', district_id: 'jhalokati', name: 'Kathalia', name_bn: 'কাঠালিয়া' },
    { id: 'nalchity', district_id: 'jhalokati', name: 'Nalchity', name_bn: 'নলছিটি' },
    { id: 'rajapur', district_id: 'jhalokati', name: 'Rajapur', name_bn: 'রাজাপুর' },
  ],
  pirojpur: [
    { id: 'pirojpur_sadar', district_id: 'pirojpur', name: 'Pirojpur Sadar', name_bn: 'পিরোজপুর সদর' },
    { id: 'bhandaria', district_id: 'pirojpur', name: 'Bhandaria', name_bn: 'ভান্ডারিয়া' },
    { id: 'kawkhali_pj', district_id: 'pirojpur', name: 'Kawkhali', name_bn: 'কাউখালী' },
    { id: 'mathbaria', district_id: 'pirojpur', name: 'Mathbaria', name_bn: 'মঠবাড়িয়া' },
    { id: 'nazirpur', district_id: 'pirojpur', name: 'Nazirpur', name_bn: 'নাজিরপুর' },
    { id: 'nesarabad', district_id: 'pirojpur', name: 'Nesarabad', name_bn: 'নেছারাবাদ' },
    { id: 'zianagar', district_id: 'pirojpur', name: 'Zianagar', name_bn: 'জিয়ানগর' },
  ],
  rangpur: [
    { id: 'rangpur_sadar', district_id: 'rangpur', name: 'Rangpur Sadar', name_bn: 'রংপুর সদর' },
    { id: 'badarganj', district_id: 'rangpur', name: 'Badarganj', name_bn: 'বদরগঞ্জ' },
    { id: 'gangachara', district_id: 'rangpur', name: 'Gangachara', name_bn: 'গঙ্গাচড়া' },
    { id: 'kaunia', district_id: 'rangpur', name: 'Kaunia', name_bn: 'কাউনিয়া' },
    { id: 'mithapukur', district_id: 'rangpur', name: 'Mithapukur', name_bn: 'মিঠাপুকুর' },
    { id: 'pirgachha', district_id: 'rangpur', name: 'Pirgachha', name_bn: 'পীরগাছা' },
    { id: 'pirganj_rp', district_id: 'rangpur', name: 'Pirganj', name_bn: 'পীরগঞ্জ' },
    { id: 'taraganj', district_id: 'rangpur', name: 'Taraganj', name_bn: 'তারাগঞ্জ' },
  ],
  dinajpur: [
    { id: 'dinajpur_sadar', district_id: 'dinajpur', name: 'Dinajpur Sadar', name_bn: 'দিনাজপুর সদর' },
    { id: 'birampur', district_id: 'dinajpur', name: 'Birampur', name_bn: 'বিরামপুর' },
    { id: 'birganj', district_id: 'dinajpur', name: 'Birganj', name_bn: 'বীরগঞ্জ' },
    { id: 'biral', district_id: 'dinajpur', name: 'Biral', name_bn: 'বিরল' },
    { id: 'bochaganj', district_id: 'dinajpur', name: 'Bochaganj', name_bn: 'বোচাগঞ্জ' },
    { id: 'chirirbandar', district_id: 'dinajpur', name: 'Chirirbandar', name_bn: 'চিরিরবন্দর' },
    { id: 'fulbari', district_id: 'dinajpur', name: 'Fulbari', name_bn: 'ফুলবাড়ী' },
    { id: 'ghoraghat', district_id: 'dinajpur', name: 'Ghoraghat', name_bn: 'ঘোড়াঘাট' },
    { id: 'hakimpur', district_id: 'dinajpur', name: 'Hakimpur', name_bn: 'হাকিমপুর' },
    { id: 'kaharole', district_id: 'dinajpur', name: 'Kaharole', name_bn: 'কাহারোল' },
    { id: 'khansama', district_id: 'dinajpur', name: 'Khansama', name_bn: 'খানসামা' },
    { id: 'nawabganj_dn', district_id: 'dinajpur', name: 'Nawabganj', name_bn: 'নবাবগঞ্জ' },
    { id: 'parbatipur', district_id: 'dinajpur', name: 'Parbatipur', name_bn: 'পার্বতীপুর' },
  ],
  gaibandha: [
    { id: 'gaibandha_sadar', district_id: 'gaibandha', name: 'Gaibandha Sadar', name_bn: 'গাইবান্ধা সদর' },
    { id: 'fulchhari', district_id: 'gaibandha', name: 'Fulchhari', name_bn: 'ফুলছড়ি' },
    { id: 'gobindaganj', district_id: 'gaibandha', name: 'Gobindaganj', name_bn: 'গোবিন্দগঞ্জ' },
    { id: 'palashbari', district_id: 'gaibandha', name: 'Palashbari', name_bn: 'পলাশবাড়ী' },
    { id: 'sadullapur', district_id: 'gaibandha', name: 'Sadullapur', name_bn: 'সাদুল্লাপুর' },
    { id: 'saghata', district_id: 'gaibandha', name: 'Saghata', name_bn: 'সাঘাটা' },
    { id: 'sundarganj', district_id: 'gaibandha', name: 'Sundarganj', name_bn: 'সুন্দরগঞ্জ' },
  ],
  kurigram: [
    { id: 'kurigram_sadar', district_id: 'kurigram', name: 'Kurigram Sadar', name_bn: 'কুড়িগ্রাম সদর' },
    { id: 'bhurungamari', district_id: 'kurigram', name: 'Bhurungamari', name_bn: 'ভুরুঙ্গামারী' },
    { id: 'char_rajibpur', district_id: 'kurigram', name: 'Char Rajibpur', name_bn: 'চর রাজিবপুর' },
    { id: 'chilmari', district_id: 'kurigram', name: 'Chilmari', name_bn: 'চিলমারী' },
    { id: 'nageshwari', district_id: 'kurigram', name: 'Nageshwari', name_bn: 'নাগেশ্বরী' },
    { id: 'phulbari_kg', district_id: 'kurigram', name: 'Phulbari', name_bn: 'ফুলবাড়ী' },
    { id: 'rajarhat', district_id: 'kurigram', name: 'Rajarhat', name_bn: 'রাজারহাট' },
    { id: 'raumari', district_id: 'kurigram', name: 'Raumari', name_bn: 'রৌমারী' },
    { id: 'ulipur', district_id: 'kurigram', name: 'Ulipur', name_bn: 'উলিপুর' },
  ],
  lalmonirhat: [
    { id: 'lalmonirhat_sadar', district_id: 'lalmonirhat', name: 'Lalmonirhat Sadar', name_bn: 'লালমনিরহাট সদর' },
    { id: 'aditmari', district_id: 'lalmonirhat', name: 'Aditmari', name_bn: 'আদিতমারী' },
    { id: 'hatibandha', district_id: 'lalmonirhat', name: 'Hatibandha', name_bn: 'হাতীবান্ধা' },
    { id: 'kaliganj_lm', district_id: 'lalmonirhat', name: 'Kaliganj', name_bn: 'কালীগঞ্জ' },
    { id: 'patgram', district_id: 'lalmonirhat', name: 'Patgram', name_bn: 'পাটগ্রাম' },
  ],
  nilphamari: [
    { id: 'nilphamari_sadar', district_id: 'nilphamari', name: 'Nilphamari Sadar', name_bn: 'নীলফামারী সদর' },
    { id: 'dimla', district_id: 'nilphamari', name: 'Dimla', name_bn: 'ডিমলা' },
    { id: 'domar', district_id: 'nilphamari', name: 'Domar', name_bn: 'ডোমার' },
    { id: 'jaldhaka', district_id: 'nilphamari', name: 'Jaldhaka', name_bn: 'জলঢাকা' },
    { id: 'kishoreganj_nl', district_id: 'nilphamari', name: 'Kishoreganj', name_bn: 'কিশোরগঞ্জ' },
    { id: 'saidpur', district_id: 'nilphamari', name: 'Saidpur', name_bn: 'সৈয়দপুর' },
  ],
  panchagarh: [
    { id: 'panchagarh_sadar', district_id: 'panchagarh', name: 'Panchagarh Sadar', name_bn: 'পঞ্চগড় সদর' },
    { id: 'atwari', district_id: 'panchagarh', name: 'Atwari', name_bn: 'আটোয়ারী' },
    { id: 'boda', district_id: 'panchagarh', name: 'Boda', name_bn: 'বোদা' },
    { id: 'debiganj', district_id: 'panchagarh', name: 'Debiganj', name_bn: 'দেবীগঞ্জ' },
    { id: 'tetulia', district_id: 'panchagarh', name: 'Tetulia', name_bn: 'তেঁতুলিয়া' },
  ],
  thakurgaon: [
    { id: 'thakurgaon_sadar', district_id: 'thakurgaon', name: 'Thakurgaon Sadar', name_bn: 'ঠাকুরগাঁও সদর' },
    { id: 'baliadangi', district_id: 'thakurgaon', name: 'Baliadangi', name_bn: 'বালিয়াডাঙ্গী' },
    { id: 'haripur', district_id: 'thakurgaon', name: 'Haripur', name_bn: 'হরিপুর' },
    { id: 'pirganj_tg', district_id: 'thakurgaon', name: 'Pirganj', name_bn: 'পীরগঞ্জ' },
    { id: 'ranisankail', district_id: 'thakurgaon', name: 'Ranisankail', name_bn: 'রানীশংকৈল' },
  ],
  mymensingh: [
    { id: 'mymensingh_sadar', district_id: 'mymensingh', name: 'Mymensingh Sadar', name_bn: 'ময়মনসিংহ সদর' },
    { id: 'bhaluka', district_id: 'mymensingh', name: 'Bhaluka', name_bn: 'ভালুকা' },
    { id: 'dhobaura', district_id: 'mymensingh', name: 'Dhobaura', name_bn: 'ধোবাউড়া' },
    { id: 'fulbaria', district_id: 'mymensingh', name: 'Fulbaria', name_bn: 'ফুলবাড়িয়া' },
    { id: 'gaffargaon', district_id: 'mymensingh', name: 'Gaffargaon', name_bn: 'গফরগাঁও' },
    { id: 'gauripur', district_id: 'mymensingh', name: 'Gauripur', name_bn: 'গৌরীপুর' },
    { id: 'haluaghat', district_id: 'mymensingh', name: 'Haluaghat', name_bn: 'হালুয়াঘাট' },
    { id: 'ishwarganj', district_id: 'mymensingh', name: 'Ishwarganj', name_bn: 'ঈশ্বরগঞ্জ' },
    { id: 'muktagachha', district_id: 'mymensingh', name: 'Muktagachha', name_bn: 'মুক্তাগাছা' },
    { id: 'nandail', district_id: 'mymensingh', name: 'Nandail', name_bn: 'নান্দাইল' },
    { id: 'phulpur', district_id: 'mymensingh', name: 'Phulpur', name_bn: 'ফুলপুর' },
    { id: 'trishal', district_id: 'mymensingh', name: 'Trishal', name_bn: 'ত্রিশাল' },
  ],
  jamalpur: [
    { id: 'jamalpur_sadar', district_id: 'jamalpur', name: 'Jamalpur Sadar', name_bn: 'জামালপুর সদর' },
    { id: 'bakshiganj', district_id: 'jamalpur', name: 'Bakshiganj', name_bn: 'বকশীগঞ্জ' },
    { id: 'dewanganj', district_id: 'jamalpur', name: 'Dewanganj', name_bn: 'দেওয়ানগঞ্জ' },
    { id: 'islampur', district_id: 'jamalpur', name: 'Islampur', name_bn: 'ইসলামপুর' },
    { id: 'madarganj', district_id: 'jamalpur', name: 'Madarganj', name_bn: 'মাদারগঞ্জ' },
    { id: 'melandaha', district_id: 'jamalpur', name: 'Melandaha', name_bn: 'মেলান্দহ' },
    { id: 'sarishabari', district_id: 'jamalpur', name: 'Sarishabari', name_bn: 'সরিষাবাড়ী' },
  ],
  netrokona: [
    { id: 'netrokona_sadar', district_id: 'netrokona', name: 'Netrokona Sadar', name_bn: 'নেত্রকোণা সদর' },
    { id: 'atpara', district_id: 'netrokona', name: 'Atpara', name_bn: 'আটপাড়া' },
    { id: 'barhatta', district_id: 'netrokona', name: 'Barhatta', name_bn: 'বারহাট্টা' },
    { id: 'durgapur_nk', district_id: 'netrokona', name: 'Durgapur', name_bn: 'দুর্গাপুর' },
    { id: 'kalmakanda', district_id: 'netrokona', name: 'Kalmakanda', name_bn: 'কলমাকান্দা' },
    { id: 'kendua', district_id: 'netrokona', name: 'Kendua', name_bn: 'কেন্দুয়া' },
    { id: 'khaliajuri', district_id: 'netrokona', name: 'Khaliajuri', name_bn: 'খালিয়াজুড়ী' },
    { id: 'mdan', district_id: 'netrokona', name: 'Mdan', name_bn: 'মদন' },
    { id: 'mohanganj', district_id: 'netrokona', name: 'Mohanganj', name_bn: 'মোহনগঞ্জ' },
    { id: 'purbadhala', district_id: 'netrokona', name: 'Purbadhala', name_bn: 'পূর্বধলা' },
  ],
  sherpur: [
    { id: 'sherpur_sadar', district_id: 'sherpur', name: 'Sherpur Sadar', name_bn: 'শেরপুর সদর' },
    { id: 'jhenaigati', district_id: 'sherpur', name: 'Jhenaigati', name_bn: 'ঝিনাইগাতী' },
    { id: 'nakla', district_id: 'sherpur', name: 'Nakla', name_bn: 'নকলা' },
    { id: 'nalitabari', district_id: 'sherpur', name: 'Nalitabari', name_bn: 'নালিতাবাড়ী' },
    { id: 'sreebardi', district_id: 'sherpur', name: 'Sreebardi', name_bn: 'শ্রীবরদী' },
  ],
};

export const useDistricts = () => {
  return useQuery({
    queryKey: ['districts'],
    queryFn: async () => bangladeshDistricts,
  });
};

export const useUpazilas = (districtId?: string) => {
  return useQuery({
    queryKey: ['upazilas', districtId],
    queryFn: async () => {
      if (!districtId) return [];
      return upazilasByDistrict[districtId] || [
        { id: `${districtId}_sadar`, district_id: districtId, name: 'Sadar', name_bn: 'সদর' },
      ];
    },
    enabled: !!districtId,
  });
};

export const useDeliverySettings = () => {
  return useQuery({
    queryKey: ['delivery-settings'],
    queryFn: () => api.get<DeliverySetting[]>('/delivery-settings').catch(() => []),
  });
};

export const getDeliveryCharge = (
  settings: DeliverySetting[] | undefined,
  isInsideDhaka: boolean
): number => {
  if (!settings || settings.length === 0) {
    return isInsideDhaka ? 60 : 120;
  }
  const type = isInsideDhaka ? 'inside_dhaka' : 'outside_dhaka';
  const setting = settings.find(s => s.delivery_type === type);
  return Number(setting?.charge) || (isInsideDhaka ? 60 : 120);
};
